# Docker Compose Override for Development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      target: production
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ENABLE_API_DOCS: true
      ENABLE_METRICS_ENDPOINT: true
    volumes:
      # Mount source code for development (hot reload)
      - ./backend:/app:delegated
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    volumes:
      # Mount frontend source for development
      - ./frontend:/usr/share/nginx/html:delegated

  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hmis_dev_db
      POSTGRES_USER: hmis_dev_user
      POSTGRES_PASSWORD: dev_password

  # Development Redis
  redis:
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev_redis_password
